# Generated by Django 3.1.7 on 2021-03-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default=str),
            preserve_default=False,
        ),
    ]
